name: Build and Deploy
on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Run commands
        run: |
          npm ci
          git config --global user.name "Anna Buyevich"
          git config --global user.email "avbuyevich@gmail.com"
          npm run deploy
