name: Build and Deploy
on: [push] 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      
      - name: Run commands
        run: |
            npm ci
            npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build

